version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_crud_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - go-crud-network

  app:
    build: .
    container_name: go-crud-api
    restart: always
    ports:
      - "8381:8381"
    environment:
      DB_USER: root
      DB_PASSWORD: dbPassword
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: go_crud_db
    depends_on:
      - mysql
    networks:
      - go-crud-network

volumes:
  mysql_data:

networks:
  go-crud-network:
    driver: bridge
